[build.environment]
NODE_VERSION = "22"
TZ = "America/New_York"

[build]
publish = "_site"
command = "npx @11ty/eleventy"

[context.production]
command = "npx @11ty/eleventy --baseUrl https://weeks.ginatrapani.org/"

[context.deploy-preview]
command = "npx @11ty/eleventy --baseUrl $DEPLOY_PRIME_URL"
